name: "document_analysis"
display_name: "Document Analysis Flow"
description: "Complete flow for document text extraction and LLM analysis"
version: "1.0.0"
author: "AI Platform Team"
tags:
  - "document"
  - "text-extraction"
  - "llm"
  - "analysis"
  - "flow"

# Flow steps
steps:
  - name: "document_extraction"
    description: "Extract text from uploaded document"
    provider: "langchain"
  - name: "llm_analysis"
    description: "Analyze extracted text with LLM"
    provider: "ollama"

# Input schema for API endpoints
inputs:
  - name: "file"
    type: "file"
    description: "Document file to analyze"
    required: true
  - name: "analysis_prompt"
    type: "string"
    description: "Analysis prompt for LLM"
    default: "Analyze this document and provide a summary"
  - name: "provider"
    type: "string"
    description: "Document extraction provider to use"
    default: "langchain"
  - name: "llm_model"
    type: "string"
    description: "LLM model to use for analysis"
    default: "mistral"
  - name: "chunk_text"
    type: "boolean"
    description: "Whether to split document into chunks"
    default: false

# Output schema
outputs:
  - name: "flow"
    type: "string"
    description: "Flow name identifier"
  - name: "steps_completed"
    type: "array"
    description: "List of successfully completed flow steps"
  - name: "extraction_result"
    type: "object"
    description: "Document text extraction results"
  - name: "llm_analysis"
    type: "object"
    description: "LLM analysis results"
  - name: "metadata"
    type: "object"
    description: "Document metadata and processing info"

# Flow configuration
config:
  timeout: 300  # 5 minutes
  retry_count: 2
  async_execution: false
  supported_formats: [".pdf", ".docx", ".doc", ".xlsx", ".xls", ".pptx", ".ppt", ".txt", ".csv", ".md", ".rtf"]
